web:
    build: ./apache
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./html:/var/www/html
    links:
     - db
    environment:
     - APP_NAME=dev
     - SERVER_NAME=dev.local
     - SERVER_ALIAS=dev.local.com
     - DOC_ROOT=/var/www/html
db:
    image: mariadb:latest
    environment:
     - MYSQL_ROOT_PASSWORD=asenha123